language: node_js
node_js: "node"
script: npm run build
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./dist
  repo: bass-dandy/portfolio-v3
  target_branch: gh-pages
  fqdn: "pizza-pizza.pizza"
  on:
    branch: master
