language: node_js
node_js: "node"
script: npm run build:prod
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./dist
  repo: naughtyfiddle/naughtyfiddle.github.io
  target_branch: master
  on:
    branch: master
